name: bbkv
title: Bund Bildender Künstler Vogtland e.V.
url: http://bbk-vogtland.de
description: Website des Bundes Bildender Künstler im Vogtland

paginate: 5
permalink: /:title
relative_permalinks: false
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap

kramdown:
  auto_ids: false

assets:
  css: /css/
  sass: /sass/
  fonts: /fonts/
  images: /img/
  javascript: /js/

loadCSS_js: true

# https://github.com/penibelst/jekyll-compress-html by Anatol Broder
compress_html:
  clippings: [html, head, title, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

defaults:
  -
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

links:
  - title: Galerie
    url: /
  - title: Projekte
    url: /projekte/
  - title: Mitglieder
    url: /mitglieder/
  - title: Verein
    url: /verein/
#  - title: Kunst in Plauen
#    url: /kunst-in-plauen/
  - title: Impressum
    url: /impressum/
