name: bbkv
title: Bund Bildender Künstler Vogtland e.V.
url: http://bbk-vogtland.de
description: Website des Bundes Bildender Künstler im Vogtland

paginate: 5
permalink: /:title
relative_permalinks: false
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap

kramdown:
  auto_ids: false

assets:
  css: /css/
  sass: /sass/
  fonts: /fonts/
  images: /img/
  javascript: /js/

google_verify: wTADCtaMlxXPgCAOE-FzFMy9uDlMS4fU3HKBDJyYAlw

loadCSS_js: true
loadFontsAsync: true

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]

sass:
  style: :compressed



defaults:
  -
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

links:
  - title: Galerie
    url: /
  - title: Projekte
    url: /projekte/
  - title: Mitglieder
    url: /mitglieder/
  - title: Verein
    url: /verein/
#  - title: Kunst in Plauen
#    url: /kunst-in-plauen/
  - title: Impressum
    url: /impressum/
