name: bbkv
title: Bund Bildender Künstler Vogtland e.V.
url: "https://bbk-vogtland.de"
description: Website des Bundes Bildender Künstler im Vogtland

paginate: 5
permalink: /:year/:title/
relative_permalinks: false
excerpt_separator: <!--more-->

exclude:
  - 'node_modules'

plugins:
  - jekyll-paginate

kramdown:
  auto_ids: false

loadCSS_js: true
loadFontsAsync: true

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

sass:
  style: :compressed



defaults:
  -
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"

links:
  - title: Galerie
    url: /
  - title: Projekte
    url: /projekte/
  - title: Mitglieder
    url: /mitglieder/
  - title: Verein
    url: /verein/
  - title: Impressum
    url: /impressum/
